<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Student\HomeworkController;
use App\Http\Controllers\Student\SubmissionController;
use App\Http\Controllers\Student\AttendanceController;
use App\Http\Controllers\Student\ClassPointsController;
use App\Http\Controllers\Student\DashboardController;
use App\Http\Controllers\language\LanguageController;
use App\Http\Controllers\dashboard\Analytics;
use App\Http\Controllers\dashboard\Crm;
use App\Http\Controllers\layouts\CollapsedMenu;
use App\Http\Controllers\layouts\ContentNavbar;
use App\Http\Controllers\layouts\ContentNavSidebar;
use App\Http\Controllers\layouts\Horizontal;
use App\Http\Controllers\layouts\Vertical;
use App\Http\Controllers\layouts\WithoutMenu;
use App\Http\Controllers\layouts\WithoutNavbar;
use App\Http\Controllers\layouts\Fluid;
use App\Http\Controllers\layouts\Container;
use App\Http\Controllers\layouts\Blank;
use App\Http\Controllers\front_pages\Landing;
use App\Http\Controllers\front_pages\Pricing;
use App\Http\Controllers\front_pages\Payment;
use App\Http\Controllers\front_pages\Checkout;
use App\Http\Controllers\front_pages\HelpCenter;
use App\Http\Controllers\front_pages\HelpCenterArticle;
use App\Http\Controllers\apps\Email;
use App\Http\Controllers\apps\Chat;
use App\Http\Controllers\apps\Calendar;
use App\Http\Controllers\apps\Kanban;
use App\Http\Controllers\apps\EcommerceDashboard;
use App\Http\Controllers\apps\EcommerceProductList;
use App\Http\Controllers\apps\EcommerceProductAdd;
use App\Http\Controllers\apps\EcommerceProductCategory;
use App\Http\Controllers\apps\EcommerceOrderList;
use App\Http\Controllers\apps\EcommerceOrderDetails;
use App\Http\Controllers\apps\EcommerceCustomerAll;
use App\Http\Controllers\apps\EcommerceCustomerDetailsOverview;
use App\Http\Controllers\apps\EcommerceCustomerDetailsSecurity;
use App\Http\Controllers\apps\EcommerceCustomerDetailsBilling;
use App\Http\Controllers\apps\EcommerceCustomerDetailsNotifications;
use App\Http\Controllers\apps\EcommerceManageReviews;
use App\Http\Controllers\apps\EcommerceReferrals;
use App\Http\Controllers\apps\EcommerceSettingsDetails;
use App\Http\Controllers\apps\EcommerceSettingsPayments;
use App\Http\Controllers\apps\EcommerceSettingsCheckout;
use App\Http\Controllers\apps\EcommerceSettingsShipping;
use App\Http\Controllers\apps\EcommerceSettingsLocations;
use App\Http\Controllers\apps\EcommerceSettingsNotifications;
use App\Http\Controllers\apps\AcademyDashboard;
use App\Http\Controllers\apps\AcademyCourse;
use App\Http\Controllers\apps\AcademyCourseDetails;
use App\Http\Controllers\apps\LogisticsDashboard;
use App\Http\Controllers\apps\LogisticsFleet;
use App\Http\Controllers\apps\InvoiceList;
use App\Http\Controllers\apps\InvoicePreview;
use App\Http\Controllers\apps\InvoicePrint;
use App\Http\Controllers\apps\InvoiceEdit;
use App\Http\Controllers\apps\InvoiceAdd;
use App\Http\Controllers\apps\UserList;
use App\Http\Controllers\apps\UserViewAccount;
use App\Http\Controllers\apps\UserViewSecurity;
use App\Http\Controllers\apps\UserViewBilling;
use App\Http\Controllers\apps\UserViewNotifications;
use App\Http\Controllers\apps\UserViewConnections;
use App\Http\Controllers\apps\AccessRoles;
use App\Http\Controllers\apps\AccessPermission;
use App\Http\Controllers\pages\UserProfile;
use App\Http\Controllers\pages\UserTeams;
use App\Http\Controllers\pages\UserProjects;
use App\Http\Controllers\pages\UserConnections;
use App\Http\Controllers\pages\AccountSettingsAccount;
use App\Http\Controllers\pages\AccountSettingsSecurity;
use App\Http\Controllers\pages\AccountSettingsBilling;
use App\Http\Controllers\pages\AccountSettingsNotifications;
use App\Http\Controllers\pages\AccountSettingsConnections;
use App\Http\Controllers\pages\Faq;
use App\Http\Controllers\pages\Pricing as PagesPricing;
use App\Http\Controllers\pages\MiscError;
use App\Http\Controllers\pages\MiscUnderMaintenance;
use App\Http\Controllers\pages\MiscComingSoon;
use App\Http\Controllers\pages\MiscNotAuthorized;
use App\Http\Controllers\authentications\LoginBasic;
use App\Http\Controllers\authentications\LoginCover;
use App\Http\Controllers\authentications\RegisterBasic;
use App\Http\Controllers\authentications\RegisterCover;
use App\Http\Controllers\authentications\RegisterMultiSteps;
use App\Http\Controllers\authentications\VerifyEmailBasic;
use App\Http\Controllers\authentications\VerifyEmailCover;
use App\Http\Controllers\authentications\ResetPasswordBasic;
use App\Http\Controllers\authentications\ResetPasswordCover;
use App\Http\Controllers\authentications\ForgotPasswordBasic;
use App\Http\Controllers\authentications\ForgotPasswordCover;
use App\Http\Controllers\authentications\TwoStepsBasic;
use App\Http\Controllers\authentications\TwoStepsCover;
use App\Http\Controllers\wizard_example\Checkout as WizardCheckout;
use App\Http\Controllers\wizard_example\PropertyListing;
use App\Http\Controllers\wizard_example\CreateDeal;
use App\Http\Controllers\modal\ModalExample;
use App\Http\Controllers\cards\CardBasic;
use App\Http\Controllers\cards\CardAdvance;
use App\Http\Controllers\cards\CardStatistics;
use App\Http\Controllers\cards\CardAnalytics;
use App\Http\Controllers\cards\CardActions;
use App\Http\Controllers\user_interface\Accordion;
use App\Http\Controllers\user_interface\Alerts;
use App\Http\Controllers\user_interface\Badges;
use App\Http\Controllers\user_interface\Buttons;
use App\Http\Controllers\user_interface\Carousel;
use App\Http\Controllers\user_interface\Collapse;
use App\Http\Controllers\user_interface\Dropdowns;
use App\Http\Controllers\user_interface\Footer;
use App\Http\Controllers\user_interface\ListGroups;
use App\Http\Controllers\user_interface\Modals;
use App\Http\Controllers\user_interface\Navbar;
use App\Http\Controllers\user_interface\Offcanvas;
use App\Http\Controllers\user_interface\PaginationBreadcrumbs;
use App\Http\Controllers\user_interface\Progress;
use App\Http\Controllers\user_interface\Spinners;
use App\Http\Controllers\user_interface\TabsPills;
use App\Http\Controllers\user_interface\Toasts;
use App\Http\Controllers\user_interface\TooltipsPopovers;
use App\Http\Controllers\user_interface\Typography;
use App\Http\Controllers\extended_ui\Avatar;
use App\Http\Controllers\extended_ui\BlockUI;
use App\Http\Controllers\extended_ui\DragAndDrop;
use App\Http\Controllers\extended_ui\MediaPlayer;
use App\Http\Controllers\extended_ui\PerfectScrollbar;
use App\Http\Controllers\extended_ui\StarRatings;
use App\Http\Controllers\extended_ui\SweetAlert;
use App\Http\Controllers\extended_ui\TextDivider;
use App\Http\Controllers\extended_ui\TimelineBasic;
use App\Http\Controllers\extended_ui\TimelineFullscreen;
use App\Http\Controllers\extended_ui\Tour;
use App\Http\Controllers\extended_ui\Treeview;
use App\Http\Controllers\extended_ui\Misc;
use App\Http\Controllers\icons\Tabler;
use App\Http\Controllers\icons\FontAwesome;
use App\Http\Controllers\form_elements\BasicInput;
use App\Http\Controllers\form_elements\InputGroups;
use App\Http\Controllers\form_elements\CustomOptions;
use App\Http\Controllers\form_elements\Editors;
use App\Http\Controllers\form_elements\FileUpload;
use App\Http\Controllers\form_elements\Picker;
use App\Http\Controllers\form_elements\Selects;
use App\Http\Controllers\form_elements\Sliders;
use App\Http\Controllers\form_elements\Switches;
use App\Http\Controllers\form_elements\Extras;
use App\Http\Controllers\form_layouts\VerticalForm;
use App\Http\Controllers\form_layouts\HorizontalForm;
use App\Http\Controllers\form_layouts\StickyActions;
use App\Http\Controllers\form_wizard\Numbered as FormWizardNumbered;
use App\Http\Controllers\form_wizard\Icons as FormWizardIcons;
use App\Http\Controllers\form_validation\Validation;
use App\Http\Controllers\tables\Basic as TablesBasic;
use App\Http\Controllers\tables\DatatableBasic;
use App\Http\Controllers\tables\DatatableAdvanced;
use App\Http\Controllers\tables\DatatableExtensions;
use App\Http\Controllers\charts\ApexCharts;
use App\Http\Controllers\charts\ChartJs;
use App\Http\Controllers\maps\Leaflet;
use App\Http\Controllers\laravel_example\UserManagement;

// ─── Auth ────────────────────────────────────────────────────────────────────
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login']);
});
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

// ─── Student portal ──────────────────────────────────────────────────────────
Route::middleware(['auth', 'student'])->group(function () {
    Route::get('/', fn() => redirect()->route('student.dashboard'));

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('student.dashboard');

    // ── Homework / Quiz ──────────────────────────────
    Route::get('/homework', [HomeworkController::class, 'index'])->name('student.homework.index');
    Route::get('/homework/{id}', [HomeworkController::class, 'view'])->name('student.homework.view');
    Route::post('/homework/{id}', [HomeworkController::class, 'submit'])->name('student.homework.submit');
    Route::get('/submission/{id}', [SubmissionController::class, 'show'])->name('student.homework.submission.view');

    // ── Attendance ───────────────────────────────────
    Route::get('/attendance', [AttendanceController::class, 'index'])->name('student.attendance');

    // ── Class Points ─────────────────────────────────
    Route::get('/class-points', [ClassPointsController::class, 'index'])->name('student.class-points');
});

// ─── Locale ───────────────────────────────────────────────────────────────────
Route::get('/lang/{locale}', [LanguageController::class, 'swap']);

// ─── Template reference (dev) ─────────────────────────────────────────────────
Route::get('/templates', [Analytics::class, 'index'])->name('templates.index');
Route::get('/dashboard/crm', [Crm::class, 'index']);
    // layouts
    Route::get('/layouts/collapsed-menu', [CollapsedMenu::class, 'index']);
    Route::get('/layouts/content-navbar', [ContentNavbar::class, 'index']);
    Route::get('/layouts/content-nav-sidebar', [ContentNavSidebar::class, 'index']);
    Route::get('/layouts/horizontal', [Horizontal::class, 'index']);
    Route::get('/layouts/vertical', [Vertical::class, 'index']);
    Route::get('/layouts/without-menu', [WithoutMenu::class, 'index']);
    Route::get('/layouts/without-navbar', [WithoutNavbar::class, 'index']);
    Route::get('/layouts/fluid', [Fluid::class, 'index']);
    Route::get('/layouts/container', [Container::class, 'index']);
    Route::get('/layouts/blank', [Blank::class, 'index']);
    // front pages
    Route::get('/front-pages/landing', [Landing::class, 'index']);
    Route::get('/front-pages/pricing', [Pricing::class, 'index']);
    Route::get('/front-pages/payment', [Payment::class, 'index']);
    Route::get('/front-pages/checkout', [Checkout::class, 'index']);
    Route::get('/front-pages/help-center', [HelpCenter::class, 'index']);
    Route::get('/front-pages/help-center-article', [HelpCenterArticle::class, 'index']);
    // apps
    Route::get('/app/email', [Email::class, 'index']);
    Route::get('/app/chat', [Chat::class, 'index']);
    Route::get('/app/calendar', [Calendar::class, 'index']);
    Route::get('/app/kanban', [Kanban::class, 'index']);
    Route::get('/app/ecommerce/dashboard', [EcommerceDashboard::class, 'index']);
    Route::get('/app/ecommerce/product/list', [EcommerceProductList::class, 'index']);
    Route::get('/app/ecommerce/product/add', [EcommerceProductAdd::class, 'index']);
    Route::get('/app/ecommerce/product/category', [EcommerceProductCategory::class, 'index']);
    Route::get('/app/ecommerce/order/list', [EcommerceOrderList::class, 'index']);
    Route::get('/app/ecommerce/order/details', [EcommerceOrderDetails::class, 'index']);
    Route::get('/app/ecommerce/customer/all', [EcommerceCustomerAll::class, 'index']);
    Route::get('/app/ecommerce/customer/details/overview', [EcommerceCustomerDetailsOverview::class, 'index']);
    Route::get('/app/ecommerce/customer/details/security', [EcommerceCustomerDetailsSecurity::class, 'index']);
    Route::get('/app/ecommerce/customer/details/billing', [EcommerceCustomerDetailsBilling::class, 'index']);
    Route::get('/app/ecommerce/customer/details/notifications', [EcommerceCustomerDetailsNotifications::class, 'index']);
    Route::get('/app/ecommerce/manage/reviews', [EcommerceManageReviews::class, 'index']);
    Route::get('/app/ecommerce/referrals', [EcommerceReferrals::class, 'index']);
    Route::get('/app/ecommerce/settings/details', [EcommerceSettingsDetails::class, 'index']);
    Route::get('/app/ecommerce/settings/payments', [EcommerceSettingsPayments::class, 'index']);
    Route::get('/app/ecommerce/settings/checkout', [EcommerceSettingsCheckout::class, 'index']);
    Route::get('/app/ecommerce/settings/shipping', [EcommerceSettingsShipping::class, 'index']);
    Route::get('/app/ecommerce/settings/locations', [EcommerceSettingsLocations::class, 'index']);
    Route::get('/app/ecommerce/settings/notifications', [EcommerceSettingsNotifications::class, 'index']);
    Route::get('/app/academy/dashboard', [AcademyDashboard::class, 'index']);
    Route::get('/app/academy/course', [AcademyCourse::class, 'index']);
    Route::get('/app/academy/course-details', [AcademyCourseDetails::class, 'index']);
    Route::get('/app/logistics/dashboard', [LogisticsDashboard::class, 'index']);
    Route::get('/app/logistics/fleet', [LogisticsFleet::class, 'index']);
    Route::get('/app/invoice/list', [InvoiceList::class, 'index']);
    Route::get('/app/invoice/preview', [InvoicePreview::class, 'index']);
    Route::get('/app/invoice/print', [InvoicePrint::class, 'index']);
    Route::get('/app/invoice/edit', [InvoiceEdit::class, 'index']);
    Route::get('/app/invoice/add', [InvoiceAdd::class, 'index']);
    Route::get('/app/user/list', [UserList::class, 'index']);
    Route::get('/app/user/view/account', [UserViewAccount::class, 'index']);
    Route::get('/app/user/view/security', [UserViewSecurity::class, 'index']);
    Route::get('/app/user/view/billing', [UserViewBilling::class, 'index']);
    Route::get('/app/user/view/notifications', [UserViewNotifications::class, 'index']);
    Route::get('/app/user/view/connections', [UserViewConnections::class, 'index']);
    Route::get('/app/access-roles', [AccessRoles::class, 'index']);
    Route::get('/app/access-permission', [AccessPermission::class, 'index']);
    // pages
    Route::get('/pages/profile-user', [UserProfile::class, 'index']);
    Route::get('/pages/profile-teams', [UserTeams::class, 'index']);
    Route::get('/pages/profile-projects', [UserProjects::class, 'index']);
    Route::get('/pages/profile-connections', [UserConnections::class, 'index']);
    Route::get('/pages/account-settings-account', [AccountSettingsAccount::class, 'index']);
    Route::get('/pages/account-settings-security', [AccountSettingsSecurity::class, 'index']);
    Route::get('/pages/account-settings-billing', [AccountSettingsBilling::class, 'index']);
    Route::get('/pages/account-settings-notifications', [AccountSettingsNotifications::class, 'index']);
    Route::get('/pages/account-settings-connections', [AccountSettingsConnections::class, 'index']);
    Route::get('/pages/faq', [Faq::class, 'index']);
    Route::get('/pages/pricing', [PagesPricing::class, 'index']);
    Route::get('/pages/misc-error', [MiscError::class, 'index']);
    Route::get('/pages/misc-under-maintenance', [MiscUnderMaintenance::class, 'index']);
    Route::get('/pages/misc-comingsoon', [MiscComingSoon::class, 'index']);
    Route::get('/pages/misc-not-authorized', [MiscNotAuthorized::class, 'index']);
    // authentications
    Route::get('/auth/login-basic', [LoginBasic::class, 'index']);
    Route::get('/auth/login-cover', [LoginCover::class, 'index']);
    Route::get('/auth/register-basic', [RegisterBasic::class, 'index']);
    Route::get('/auth/register-cover', [RegisterCover::class, 'index']);
    Route::get('/auth/register-multisteps', [RegisterMultiSteps::class, 'index']);
    Route::get('/auth/verify-email-basic', [VerifyEmailBasic::class, 'index']);
    Route::get('/auth/verify-email-cover', [VerifyEmailCover::class, 'index']);
    Route::get('/auth/reset-password-basic', [ResetPasswordBasic::class, 'index']);
    Route::get('/auth/reset-password-cover', [ResetPasswordCover::class, 'index']);
    Route::get('/auth/forgot-password-basic', [ForgotPasswordBasic::class, 'index']);
    Route::get('/auth/forgot-password-cover', [ForgotPasswordCover::class, 'index']);
    Route::get('/auth/two-steps-basic', [TwoStepsBasic::class, 'index']);
    Route::get('/auth/two-steps-cover', [TwoStepsCover::class, 'index']);
    // wizards
    Route::get('/wizard/ex-checkout', [WizardCheckout::class, 'index']);
    Route::get('/wizard/ex-property-listing', [PropertyListing::class, 'index']);
    Route::get('/wizard/ex-create-deal', [CreateDeal::class, 'index']);
    // modal / cards
    Route::get('/modal-examples', [ModalExample::class, 'index']);
    Route::get('/cards/basic', [CardBasic::class, 'index']);
    Route::get('/cards/advance', [CardAdvance::class, 'index']);
    Route::get('/cards/statistics', [CardStatistics::class, 'index']);
    Route::get('/cards/analytics', [CardAnalytics::class, 'index']);
    Route::get('/cards/actions', [CardActions::class, 'index']);
    // UI
    Route::get('/ui/accordion', [Accordion::class, 'index']);
    Route::get('/ui/alerts', [Alerts::class, 'index']);
    Route::get('/ui/badges', [Badges::class, 'index']);
    Route::get('/ui/buttons', [Buttons::class, 'index']);
    Route::get('/ui/carousel', [Carousel::class, 'index']);
    Route::get('/ui/collapse', [Collapse::class, 'index']);
    Route::get('/ui/dropdowns', [Dropdowns::class, 'index']);
    Route::get('/ui/footer', [Footer::class, 'index']);
    Route::get('/ui/list-groups', [ListGroups::class, 'index']);
    Route::get('/ui/modals', [Modals::class, 'index']);
    Route::get('/ui/navbar', [Navbar::class, 'index']);
    Route::get('/ui/offcanvas', [Offcanvas::class, 'index']);
    Route::get('/ui/pagination-breadcrumbs', [PaginationBreadcrumbs::class, 'index']);
    Route::get('/ui/progress', [Progress::class, 'index']);
    Route::get('/ui/spinners', [Spinners::class, 'index']);
    Route::get('/ui/tabs-pills', [TabsPills::class, 'index']);
    Route::get('/ui/toasts', [Toasts::class, 'index']);
    Route::get('/ui/tooltips-popovers', [TooltipsPopovers::class, 'index']);
    Route::get('/ui/typography', [Typography::class, 'index']);
    // extended UI
    Route::get('/extended/ui-avatar', [Avatar::class, 'index']);
    Route::get('/extended/ui-blockui', [BlockUI::class, 'index']);
    Route::get('/extended/ui-drag-and-drop', [DragAndDrop::class, 'index']);
    Route::get('/extended/ui-media-player', [MediaPlayer::class, 'index']);
    Route::get('/extended/ui-perfect-scrollbar', [PerfectScrollbar::class, 'index']);
    Route::get('/extended/ui-star-ratings', [StarRatings::class, 'index']);
    Route::get('/extended/ui-sweetalert2', [SweetAlert::class, 'index']);
    Route::get('/extended/ui-text-divider', [TextDivider::class, 'index']);
    Route::get('/extended/ui-timeline-basic', [TimelineBasic::class, 'index']);
    Route::get('/extended/ui-timeline-fullscreen', [TimelineFullscreen::class, 'index']);
    Route::get('/extended/ui-tour', [Tour::class, 'index']);
    Route::get('/extended/ui-treeview', [Treeview::class, 'index']);
    Route::get('/extended/ui-misc', [Misc::class, 'index']);
    // icons
    Route::get('/icons/tabler', [Tabler::class, 'index']);
    Route::get('/icons/font-awesome', [FontAwesome::class, 'index']);
    // forms
    Route::get('/forms/basic-inputs', [BasicInput::class, 'index']);
    Route::get('/forms/input-groups', [InputGroups::class, 'index']);
    Route::get('/forms/custom-options', [CustomOptions::class, 'index']);
    Route::get('/forms/editors', [Editors::class, 'index']);
    Route::get('/forms/file-upload', [FileUpload::class, 'index']);
    Route::get('/forms/pickers', [Picker::class, 'index']);
    Route::get('/forms/selects', [Selects::class, 'index']);
    Route::get('/forms/sliders', [Sliders::class, 'index']);
    Route::get('/forms/switches', [Switches::class, 'index']);
    Route::get('/forms/extras', [Extras::class, 'index']);
    Route::get('/form/layouts-vertical', [VerticalForm::class, 'index']);
    Route::get('/form/layouts-horizontal', [HorizontalForm::class, 'index']);
    Route::get('/form/layouts-sticky', [StickyActions::class, 'index']);
    Route::get('/form/wizard-numbered', [FormWizardNumbered::class, 'index']);
    Route::get('/form/wizard-icons', [FormWizardIcons::class, 'index']);
    Route::get('/form/validation', [Validation::class, 'index']);
    // tables / charts / maps
    Route::get('/tables/basic', [TablesBasic::class, 'index']);
    Route::get('/tables/datatables-basic', [DatatableBasic::class, 'index']);
    Route::get('/tables/datatables-advanced', [DatatableAdvanced::class, 'index']);
    Route::get('/tables/datatables-extensions', [DatatableExtensions::class, 'index']);
    Route::get('/charts/apex', [ApexCharts::class, 'index']);
    Route::get('/charts/chartjs', [ChartJs::class, 'index']);
    Route::get('/maps/leaflet', [Leaflet::class, 'index']);
    // laravel example
Route::get('/laravel/user-management', [UserManagement::class, 'UserManagement']);
Route::resource('/user-list', UserManagement::class);
