<?php
// Variables
return [
  "creatorName" => "Code Ninja Pro",
  "creatorUrl" => "https://codeninja.pro",
  "templateName" => "Code Ninja Pro",
  "templateSuffix" => "Student Portal",
  "templateVersion" => "3.0.0",
  "templateFree" => false,
  "templateDescription" => "Code Ninja Pro's student portal — homework, attendance, calendar and more.",
  "templateKeyword" => "",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "moreThemes" => "",
  "ogTitle" => "Code Ninja Pro — Student Portal",
  "ogImage" => "",
  "ogType" => "website",
  "documentation" => "",
  "generator" => "",
  "changelog" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => ""
];
